script-dir: /opt/ci/config/modules/openstack_project/files/nodepool/scripts/
dburi: 'mysql://nodepool@localhost/nodepool'

cron:
  check: '*/1 * * * *'

zmq-publishers:
  - tcp://127.0.0.1:8888

gearman-servers:
  - host: 127.0.0.1

providers:
  - name: ci-lab
    username: 'ci-user'
    password: 'nova'
    auth-url: 'http://172.18.168.42:5000/v2.0'
    project-id: 'ci'
    max-servers: 6
    boot-timeout: 120
    net-id: bd53083d-e211-4053-acad-d18f45191aed
    floating-pool: public
    use-neutron: true
    images:
      - name: precise
        base-image: 'ubuntu-12.04'
        min-ram: 4096
        private-key: '/var/lib/jenkins/.ssh/id_dsa'
        setup: prepare_node_bare.sh
      - name: precise-itests
        base-image: 'ubuntu-12.04'
        min-ram: 2048
        private-key: '/var/lib/jenkins/.ssh/id_dsa'
        setup: prepare_node_bare.sh

targets:
  - name: savanna-gate
    jenkins:
      url: http://127.0.0.1:8080/
      user: admin
      apikey: JENKINS_API_KEY
    images:
      - name: precise-itests
        min-ready: 3
        providers:
          - name: ci-lab
      - name: precise
        min-ready: 3
        providers:
          - name: ci-lab
